# This is a CI workflow for the NCEPLIBS-ip project.
#
# CDash
#

name: cdash
on:
  push:
    branches:
    - cdash

jobs:
  cdash:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc
      CDASH_TOKEN: ${{ secrets.CDASH_TOKEN }}

    steps:

    - name: Cache test files
      uses: actions/cache@v4
      with:
        path: ip-test-data-20241230.tgz
        key: NCEPLIBS-ip-test-files-1

    - name: CDash
      uses: AlexanderRichert-NOAA/ci-cdash@develop
      with:
        package-name: NCEPLIBS-ip
        extra-cmake-options: -DFTP_TEST_FILES=ON -DTEST_FILES_CACHE=${{ github.workspace }}/ip-test-data-20241230.tgz
        extra-apt-packages: libopenblas-serial-dev
