# This is a CI workflow for the NCEPLIBS-ip project.
#
# This workflow builds with the Intel Classic and OneAPI compilers.
#
# Ed Hartnett, 1/8/23
name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openmp: [ ON, OFF ]
        compilers: ["oneapi", "classic"]

    steps:

    - name: "Install Intel"
      uses: NOAA-EMC/ci-install-intel-toolkit@develop
      with:
        compiler-setup: ${{ matrix.compilers }}

    - name: checkout
      uses: actions/checkout@v4
      with: 
        path: ip

    - name: build
      run: |
        cmake -S ip -B ip/build -DOPENMP=${{ matrix.openmp }} -DBUILD_SHARED_LIBS=OFF -DBUILD_8=ON
        cmake --build ip/build --parallel 2 --verbose
    
    - name: test
      run: |
        ulimit -s unlimited
        ctest --test-dir ip/build --verbose --output-on-failure --rerun-failed
