# This is a CI workflow for the NCEPLIBS-ip project.
#
# This workflow builds with the Intel Classic and OneAPI compilers.
#
# Ed Hartnett, 1/8/23
name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Cancel in-progress workflows when pushing to a branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openmp: [ ON, OFF ]
        compilers: ["oneapi", "classic"]

    steps:

    - name: "Install Intel"
      uses: NOAA-EMC/ci-install-intel-toolkit@develop
      with:
        compiler-setup: ${{ matrix.compilers }}

    - name: checkout
      uses: actions/checkout@v4
      with: 
        path: ip

    - name: Cache test files
      uses: actions/cache@v4
      with:
        path: testfiles.tgz
        key: NCEPLIBS-ip-test-files-1

    - name: build
      run: |
        sudo apt install libopenblas-serial-dev
        if [ ! -f testfiles.tgz ]; then wget https://ftp.emc.ncep.noaa.gov/static_files/public/NCEPLIBS-ip/ip-test-data-20241230.tgz -O testfiles.tgz ; fi
        cmake -S ip -B ip/build -DOPENMP=${{ matrix.openmp }} -DBUILD_SHARED_LIBS=OFF -DBUILD_8=ON -DFTP_TEST_FILES=ON -DTEST_FILES_CACHE=$GITHUB_WORKSPACE/testfiles.tgz
        cmake --build ip/build --parallel 2 --verbose
    
    - name: test
      run: |
        ulimit -s unlimited
        ctest --test-dir ip/build --verbose --output-on-failure --rerun-failed
