# This is a CI workflow for the NCEPLIBS-ip project.
#
# This workflow builds on Linux with different options.
#
# Ed Hartnett, 1/8/23
name: Linux
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Linux:
    runs-on: ubuntu-latest
    env:
      FC: gfortran-10
      CC: gcc-10

    strategy:
      matrix:
        openmp: [ ON, OFF ]
        options: [ -DBUILD_D=OFF, -DBUILD_4=OFF, -DBUILD_8=ON ]
        
    steps:

    - name: checkout
      uses: actions/checkout@v2
      with: 
        path: ip

    - name: build
      run: |
        sudo apt install libopenblas-serial-dev
        cd ip
        mkdir build 
        cd build
        cmake -DCMAKE_PREFIX_PATH="~/" -DOPENMP=${{ matrix.openmp }} ${{ matrix.options }} -DCMAKE_INSTALL_PREFIX=~/install ..
        make -j2 VERBOSE=1
        make install
        if [ $(grep -c "BLA_VENDOR OpenBLAS" ~/install/lib/cmake/ip/ip-config.cmake) -eq 0 ]; then
          echo "OpenBLAS not set as BLA_VENDOR in ip-config.cmake!"
          exit 1
        fi
    
    - name: test
      run: |
        cd $GITHUB_WORKSPACE/ip/build
        ctest --verbose --output-on-failure --rerun-failed
