# This is a CI workflow for the NCEPLIBS-ip project.
#
# This workflow builds on MacOS with different options.
#
# Ed Hartnett, 1/8/23
name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-12
      CC: gcc-12
    strategy:
      matrix:
        openmp: [ ON, OFF ]
        sharedlibs: [ON, OFF]
        
    steps:
      
    - name: checkout
      uses: actions/checkout@v4
      with: 
        path: ip

    - name: build
      run: |
        cmake -S ip -B ip/build -DOPENMP=${{ matrix.openmp }} -DBUILD_SHARED_LIBS=${{ matrix.sharedlibs }} -DCMAKE_INSTALL_PREFIX=~/install -DBUILD_8=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build ip/build --parallel 2 --verbose
        cmake --install ip/build
        ls -l ~/install
        ls -l ~/install/lib
    
    - name: test
      run: ctest --test-dir ip/build --parallel 2 --verbose --output-on-failure --rerun-failed
