# This is a CI workflow for the NCEPLIBS-ip project.
#
# This workflow builds on MacOS with different options.
#
# Ed Hartnett, 1/8/23
name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-11
      CC: gcc-11
    strategy:
      matrix:
        openmp: [ ON, OFF ]
        sharedlibs: [ON, OFF]
        
    steps:
      
    - name: checkout
      uses: actions/checkout@v2
      with: 
        path: ip

    - name: build
      run: |
        cd ip
        mkdir build 
        cd build
        cmake -DOPENMP=${{ matrix.openmp }} -DBUILD_SHARED_LIBS=${{ matrix.sharedlibs }} -DCMAKE_INSTALL_PREFIX=~/install -DBUILD_8=ON -DCMAKE_BUILD_TYPE=Debug ..
        make -j2 VERBOSE=2
        make install
        ls -l ~/install
        ls -l ~/install/lib
    
    - name: test
      run: |
        cd $GITHUB_WORKSPACE/ip/build
        ctest --verbose --output-on-failure --rerun-failed
